version: '3.9'

networks:
  net:
    driver: bridge
services:

  app_proxy:
    environment:
      APP_HOST: chromadb
      APP_PORT: 8000

  chromadb:
    image: chromadb/chroma:0.5.13
    user: "1000:1000"
    init: true
    volumes:
      - ./chromadb:/chroma/chroma
    environment:
      
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma # this is the default path, change it as needed
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-TRUE}
    ports:
      - 8000:8000
    networks:
      - net